# Generated by Django 6.0.2 on 2026-02-24 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40, verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Masalan: +998901234567', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam formati: +998901234567 bo'lishi kerak.", regex='^\\+998\\d{9}$')])),
                ('subject', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni: ')),
            ],
        ),
    ]
