# Generated by Django 6.0.2 on 2026-02-24 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageforme',
            name='phone',
            field=models.CharField(help_text='Masalan: +998901234567', max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam formati: +998901234567 bo'lishi kerak.", regex='^\\+998\\d{9}$')]),
        ),
    ]
